sudo: false
language: perl
perl:
    - "5.38.2"
install:
    - cpanm -q -n Dist::Zilla 
    - dzil authordeps --missing | cpanm -q -n
    - dzil listdeps --author --missing | cpanm -q -n
script:
    - dzil test --all
